name: calorie_calculator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.10
  provider: ^6.1.5
  intl: ^0.20.2
  
  # --- 6 บรรทัดนี้ถูกลบออกแล้ว ---
  # path: ^1.9.1
  # sqflite: ^2.4.2
  # path_provider: ^2.1.5
  # shared_preferences: ^2.5.3
  # sqflite_common_ffi: ^2.3.6
  # sqflite_common_ffi_web: ^1.0.0
  # --------------------------------
  
  fl_chart: ^1.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # นี่คือการบอก Flutter ว่าให้รวมไฟล์ทั้งหมดในโฟลเดอร์ assets/images/

flutter_launcher_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/app_icon.png" 
  min_sdk_android: 21